### ISSUE TITLE
[Gotenberg] gotenberg/gotenberg-php missing 

### ISSUE THREAD

**Issue by matthiashamacher** [pimcore/web-to-print-bundle#30]
If you want to use the gotenberg Adapter it is currently not working because the gotenberg/gotenberg-php package is only installed in dev. 

Either the package needs to be moved to require or the [documentation](https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/System_Setup_and_Hosting/Additional_Tools_Installation/#gotenberg) needs to be updated that the package needs to be installed manually in the project to use the adapter.

The Chromium adapter potentially has the same issue, but I haven't checked that.

I'm willing to make the required changes but need input which way you want to go.

**Comment by kingjia90** [comment]
Thank you for the report! 

We were coincidentally working on improving a little bit the [documentation ](https://github.com/pimcore/pimcore/pull/15277), but in the meanwhile, if you could add some links to the core from this bundle in the installation page that would be great.

Won't be bad if the entries composer [suggest](https://github.com/pimcore/pimcore/blob/9b1d3eb47626ed5386448d396c7100d8ebefbd23/composer.json#L155-L157) are also copied in the composer of this bundle, right? there's no sort of "inheritance" or so?

**Comment by matthiashamacher** [comment]
@kingjia90 Added some more documentation and the suggest. I would also propose to at least remove the suggest for the chromium dependency from `pimcore/pimcore` as it is not required for the core. As gotenberg can be used for the document preview I think that one can stay.
