### ISSUE TITLE
Print Page Issue In Pimcore (Web-to-Print)

### ISSUE THREAD

**Issue by KasthuriAnandhan** [pimcore/web-to-print-bundle#42]
@fashxp

Hi Christian Fasching, there is no print pages in documents of the pimcore, except this everything will be showed how to add print pages I have installed web-to-print bundle also but can't to view the print pages in documents of the pimcore, can you please help me to resolve this issue and kindly provide the Web-to-print-settings configuration which is under the settings of the pimcore. Below I have attached the screen shots of my enterprise pimcore and demo version documents.

**My Enterprise Pimcore's Document**
![Screenshot ](https://github.com/pimcore/web-to-print-bundle/assets/125338676/db978a9c-7382-454b-ac15-f58d62a14706)

**Demo version Pimcore's Document**
![Untitled](https://github.com/pimcore/web-to-print-bundle/assets/125338676/641fca37-e090-4bd4-b3ab-d66fedfac813)

Can you see the difference between these two, kindly give the solution to enable print pages.

**Comment by KasthuriAnandhan** [comment]
@fashxp

Can you help me here to resolve the above issue.

**Comment by kingjia90** [comment]
Looks like it's not installed properly
Can you share the output of the command `bin/console pimcore:bundle:list`?

should look like this
![image](https://github.com/pimcore/web-to-print-bundle/assets/6014195/b4402149-9837-41df-b435-e44a7d7fb9df)

Did you upgrade from Pimcore 10 or is a new project based on 11?

**Comment by KasthuriAnandhan** [comment]
yeah sure

**Comment by KasthuriAnandhan** [comment]
![Screenshot 2023-07-20 133651](https://github.com/pimcore/web-to-print-bundle/assets/125338676/d4e825b1-91b4-4c0c-9ce2-0a9816465a76)

**Comment by kingjia90** [comment]
Ahh, you are on 10.x, then you have to go under `Settings > Web-to-Print` and there's a checkbox on top of the page. 
The functionalities are not activated by default

**Comment by kingjia90** [comment]
Ahh you are on 10.x, then you have to go under `Settings > Web-to-Print Settings` and activate by clicking on the first checkbox on top of that page. 
https://pimcore.com/docs/pimcore/10.6/Development_Documentation/Documents/Document_Types/Print_Documents.html

The web-to-print functionalities are not activated by default.

**Comment by KasthuriAnandhan** [comment]
![Screenshot 2023-07-20 134017](https://github.com/pimcore/web-to-print-bundle/assets/125338676/828c3837-b48e-41e6-aa46-1054da6b6652)

Sorry before I have shared the wrong screen shot

**Comment by KasthuriAnandhan** [comment]
> Ahh you are on 10.x, then you have to go under `Settings > Web-to-Print` and activate by clicking on the first checkbox on top of that page. The web-to-print functionalities are not activated by default.

I was activated that and tried but then also can't to see the Add Printpage option in Documents.

**Comment by KasthuriAnandhan** [comment]
![Screenshot 2023-07-20 134259](https://github.com/pimcore/web-to-print-bundle/assets/125338676/1e359ffb-bd44-4564-a4b9-30d8b0c71762)

Is my configuration are right or wrong, or I should change anything.

**Comment by kingjia90** [comment]
Then please check the console under Browser Developers Tools F12, there could be a javascript error that prevents the menu building

**Comment by KasthuriAnandhan** [comment]
![Screenshot 2023-07-20 134729](https://github.com/pimcore/web-to-print-bundle/assets/125338676/4a1223d1-07df-4579-850b-6271ca01b063)

**Comment by KasthuriAnandhan** [comment]
Can you please help me to enable printpages.

**Comment by kingjia90** [comment]
Console doesn't look bad 
![image](https://github.com/pimcore/web-to-print-bundle/assets/6014195/b5a5f26a-81b3-4e54-a3f7-e84b685608c6)
, then suggesting to check the custom views and perspective.


I am closing here and moving the discussion to the already open https://github.com/pimcore/pimcore/discussions/15568 since this repository is mainly for the extracted bundle from Pimcore 11

**Comment by KasthuriAnandhan** [comment]
yeah okay, now what should I do to enable printpages in the documents.
