### ISSUE TITLE
Ease adding of new processors

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/web-to-print-bundle#44]
The existing processors are hardcoded at various places like https://github.com/pimcore/web-to-print-bundle/blob/4f46683fff81c6b88d537251a47d6da107a98720/src/Processor.php#L39
https://github.com/pimcore/web-to-print-bundle/blob/4f46683fff81c6b88d537251a47d6da107a98720/src/Processor.php#L47

Otherwise we could easily use a new Processor Class (using dompdf or wkhtmltopdf) with this bundle by simply extending Pimcore\Bundle\WebToPrintBundle\Processor and implementing the functions.

Currently we'd need to fork the complete repository as far as I can see. What do you think?

I'd be happy to provide a PR (need to touch all processor definitions code anyway to add a new one).

**Comment by fashxp** [comment]
We could try to switch so tagged services and a service locator? 
We would love to see a PR for that.

**Comment by Cruiser13** [comment]
@kingjia90 we added our PR in october last year. Half a year passed and it's merged but still not available (no 1.2.0 release).
We still manually patch several pimcore 11 instances using this code. Any chance to get a 1.2.0 release including this code soon?
Or should we better fork the repository and use it on our own in the future as it's not actively maintained?

**Comment by fashxp** [comment]
release is actually planned next week, and it also will be part of platform version release 2024.1 later this month.

**Comment by Cruiser13** [comment]
@fashxp thank you!
