### ISSUE TITLE
Settings > Web-to-Print not showing

### ISSUE THREAD

**Issue by CesarABian** [pimcore/web-to-print-bundle#51]
After having installed pimcore 11 (skeleton), I installed the bundle pimcore/web2print-tools-bundle:^5.0 and I cannot see the configuration in the UI

**Comment by kingjia90** [comment]
> I installed the bundle pimcore/web2print-tools-bundle:^5.0 

`web-to-print-bundle` and `web2print-tools-bundle` are 2 "separate" things at the moment, it looks like that you may be confusing one with the other.
Please install `web-to-print-bundle` as well (`composer require` and add the entry in `bundles.php`) and try again, if it still doesn't work, please open a new issue with more details.

In the case that the stuff related to the web2print tools are not appearing, then please open a new issue in that repository https://github.com/pimcore/web2print-tools/issues
