### ISSUE TITLE
PDF download

### ISSUE THREAD

**Issue by JasminBektic** [pimcore/web-to-print-bundle#52]
When downloading document the error is shown:
![image](https://github.com/pimcore/web-to-print-bundle/assets/20265277/1943177a-c0a2-4303-bc25-9c92c0e5875c)

Seems like route name [pimcore_bundle_document_printpage_pdfdownload](https://github.com/pimcore/web-to-print-bundle/blob/4f46683fff81c6b88d537251a47d6da107a98720/public/js/document/printpages/pdf_preview.js#L95C80-L95C80) doesn't match routing list

![image](https://github.com/pimcore/web-to-print-bundle/assets/20265277/3fb07287-de63-4637-b76b-1ec2973c751d)

**Comment by JasminBektic** [comment]
https://github.com/pimcore/web-to-print-bundle/pull/54

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/web-to-print-bundle/pull/54

Thank you again!
