### ISSUE TITLE
Possible bug in default options: preferCssPageSize

### ISSUE THREAD

**Issue by schmidt-travixmedia** [pimcore/web-to-print-bundle#60]
https://github.com/pimcore/web-to-print-bundle/blob/932016003cdbfa947570c7a32bbf2baa9cb67a8e/src/Processor/Chromium.php#L151C12-L151C42

Shouldn't this line be
`preferCssPageSize` (correct camel case)
instead of
`preferCSSPageSize` ?

**Comment by blankse** [comment]
@schmidt-travixmedia No, this is correct. This is a option of the https://github.com/chrome-php/chrome dependency.
See the README there.
